Movie.create!([
  {title: "Die Hard", rating: "R", total_gross: "79000000.0", description: "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles. ", released_on: "1993-05-04", cast: " Bruce Willis, Alan Rickman, Bonnie Bedelia ", director: "John McTiernan", duration: "121", image_file_name: "diehard.jpg"},
  {title: "Green Fried Tomatoes", rating: "PG-13", total_gross: "74000000.0", description: "A housewife who is unhappy with her life befriends an old lady in a nursing home and is enthralled by the tales she tells of people she used to know. ", released_on: "1990-06-01", cast: " Kathy Bates, Jessica Tandy, Mary Stuart Masterson", director: "Pedro Almodóvar", duration: "140", image_file_name: "green.jpg"},
  {title: "Water World", rating: "PG-13", total_gross: "100000000.0", description: "In a future where the polar ice-caps have melted and Earth is almost entirely submerged, a mutated mariner fights starvation and outlaw smokers, and reluctantly helps a woman and a young girl try to find dry land.", released_on: "1998-05-06", cast: " Kevin Costner, Jeanne Tripplehorn, Dennis Hopper", director: "Kevin Reynolds", duration: "180", image_file_name: "waterworld.jpg"},
  {title: "Brat 2", rating: "R", total_gross: "70000000.0", description: "Arriving in Moscow, Danila discovers Konstantin dead and he sets out to avenge his death; a journey that leads him to Chicago and a whole new experience.", released_on: "2000-05-06", cast: " Sergey Bodrov, Viktor Sukhorukov, Sergey Makovetskiy", director: "Aleksey Balabanov", duration: "120", image_file_name: "brat2.jpg"},
  {title: "Looper", rating: "R", total_gross: "884000000.0", description: "In 2074, when the mob wants to get rid of someone, the target is sent into the past, where a hired gun awaits - someone like Joe - who one day learns the mob wants to 'close the loop' by sending back Joe's future self for assassination. ", released_on: "2012-05-06", cast: "Joseph Gordon-Levitt, Bruce Willis, Emily Blunt", director: "Rian Johnson", duration: "120", image_file_name: "looper.jpg"},
  {title: "Total Recall", rating: "R", total_gross: "80000000.0", description: "When a man goes for virtual vacation memories of the planet Mars, an unexpected and harrowing series of events forces him to go to the planet for real - or does he? ", released_on: "1995-05-06", cast: " Arnold Schwarzenegger, Sharon Stone, Michael Ironside", director: "Paul Verhooven", duration: "130", image_file_name: "totalrecall.jpg"},
  {title: "Fast and the Furious 15", rating: "R", total_gross: "140000000.0", description: "Moon police officer Brian O'Conner must decide where his loyalty really lies when he becomes enamored with the street racing world he has been sent undercover to destroy. ", released_on: "2024-06-14", cast: "Brian O'Conner, Vin Diesel", director: "Fred Manson", duration: "150", image_file_name: ""}
])
Review.create!([
  {name: "Daniel Pickens", stars: 4, comment: "I have read all comments and realised that not many western people got the message from the film. Probably that was because film's poor subtitles or translation and lack information or knowledge about real life in Russia and post Soviet countries. Maybe following explanation will help to clear couple of things.", movie_id: 4, location: nil},
  {name: "Vlad Pobens", stars: 5, comment: "Dear Viewers, such a movie asks for a pretty complex comment, and I apologize for the length in advance to all the readers for that reason. First of all, if made in Hollywood, this movie would become the absolute Oscar winner and total mocking at Russians.", movie_id: 4, location: nil},
  {name: "Mark Sullen", stars: 5, comment: "This is an excellent film and one that will stand the test of time. Brilliant acting, story and filming and one of my top 10 foreign language films without a doubt. A road movie from East to West with an unlikely hero you can root for, on a mission against the odds in a situation thats not been done before, with great action scenes, fantastic soundtrack and top acting. Best Russian language film of 2000's and one that anyone interested in Russian or European cinema must see.", movie_id: 4, location: nil},
  {name: "Brandon D.", stars: 4, comment: "\"Waterworld\" is one of those movies that everyone would rather passively make fun of rather than take the time to watch. This is unfortunate, because it really is a good movie. Sure, it's borrowing a lot from \"Mad Max,\" but it's not like \"Mad Max\" was original fare to begin with.", movie_id: 3, location: nil},
  {name: "Rupert Sommer", stars: 3, comment: "I want the Costner bashers to sit down and watch \"Rebirth of the Mothra III\" on Sci-Fi Channel some time. Then they'll know that they have seen the worst movie ever made.\r\n\r\n\"Waterworld\" is an escapist fantasy/action picture, not unlike the James Bond and Indiana Jones pictures. Costner's performance works on exactly the same level as the Connery/Moore/Brosnan portrayals of 007 and Harrison Ford's portrayal of Indy -- straightforward, grim, stoic, a little mean-spirited, a little cruel, unafraid of dirt, grime, death, or salt water.", movie_id: 3, location: nil},
  {name: "Susan Livid", stars: 5, comment: "I enjoyed this movie immensely. This is one of the best examples of storytelling that I have seen. The structure of the movie - alternating between the past and present, with multiple intertwining plots - keeps the viewer hooked on how the story will unfold. It unfolds gracefully and is enjoyable throughout.\r\n\r\nThe acting is exceptional. Mary Stuart Masterson and Mary Louise Parker carry the bulk of the acting load. They are fantastic. The relationship between these very different young women is complex and satisfying.", movie_id: 2, location: nil},
  {name: "Mary Lands", stars: 3, comment: "This movie is beyond anything that I have ever viewed in my entire life. Usually, this sort of movie isn't the kind that I look at, but I fell in love with the story and the characters, as well as the wonderful actresses (Kathy Bates, Jessica Tandy, Mary Stuart Masterson, and Mary-Louise Parker) who did an outstanding job portraying their characters in a unique and unforgettable way.\r\n\r\nSince I don't want to spoil anything for those who haven't seen it, let me just say that it's an astounding tale of a special friendship that goes way beyond what we would call a \"regular\" one. It will make you thankful for the friends you have and even give women a sense to stand up for their own rights. All in all, I give this movie a 10 out of 10. If you haven't seen it, what are you doing reading this?! Go out and rent it!", movie_id: 2, location: nil},
  {name: "Jack F.", stars: 5, comment: "\"Fantastic, I'm totally blown away by Total Recall.\"", movie_id: 6, location: nil},
  {name: "Julie Parson", stars: 4, comment: "Set during an unspecified future era, Douglas Quaid (Arnold Schwarzenegger) is a construction worker who longs for a trip to Mars. His wife, Lori (Sharon Stone) isn't so keen on it--she'd prefer a trip to Saturn, or a space cruise. Riding on the subway one day, Quaid notices a television advertisement for a company named Rekall, which specializes in memory implants of vacations.", movie_id: 6, location: nil},
  {name: "Jewell Landy", stars: 4, comment: "Quite possibly the best modern action movie since the classic \"Dirty Harry\", \"Die Hard\" simply rocks. Based on the interesting novel \"Nothing Lasts Forever\" by Roderick Thorp, \"Die Hard\" made headlines for its combination of a terrific cast, excellent script, amazing action sequences and superb direction.", movie_id: 1, location: nil},
  {name: "Reid Johnson", stars: 5, comment: "One could claim that 1988's \"Die Hard\" is one of the most influential action movies ever made because it basically revolutionized one of the most copied (but never matched, at least in terms of quality) formulas: a loner, by some unique twist of fate, battles it out with an \"x\" number of terrorists in an enclosed environment.", movie_id: 1, location: nil},
  {name: "John Mcbane", stars: 3, comment: "Even if the non-action parts are a tad slow in comparison, that is more than compensated by so many things that makes Water World so brilliant.", movie_id: 3, location: nil}
])
